project:
  type: website

website:
  title: "course_template"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: 
      light: [flatly, styles/light.scss]
      dark: [darly, styles/dark.scss]
    css: styles/styles.css
    toc: true

editor: visual

