project:
  type: website
  preview:
    port: 7777

execute: 
  freeze: auto

license: CC-BY 4.0
author: 
  name: Josef Fruehwald
  
execute: 
  freeze: auto

website:
  # announcement: 
  #   content: "**Coming up!** |" 
  #   icon: box-arrow-right
  #   position: below-navbar
  #   dismissable: true
  #   type: success
  favicon: /assets/logo.svg
  image:  /assets/logo.svg
  title: "course_template"
  reader-mode: true
  # site-url: https://lorg.github.io/
  # repo-url: https://github.com/org/org.github.io
  twitter-card: 
    image: /assets/logo.svg
  open-graph:
    image: /assets/logo.svg
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Notes"
        href: notes/index.qmd
      - text: "About"
        href: about.qmd
  sidebar: 
    - title: "Home"
      style: "docked"    
      logo: assets/logo.svg    
      contents:
        - text: Home
          href: index.qmd
        - href: syllabus/syllabus.qmd
          text: Syllabus
        - href: syllabus/schedule.qmd
          text: Schedule
    - title: "Notes"
      contents:
        - text: Notes Home
          href: notes/index.qmd
        - section: Class Meetings
          contents: 
            - auto: notes/meetings/*

format:
  html:
    theme: 
      light: 
        - flatly
        - styles/custom.scss
        - styles/light.scss
      dark:
        - flatly
        - styles/custom.scss
        - styles/light.scss    
    css: styles/styles.css
    toc: true
    grid:
      body-width: 900px    
    fontsize: large
    link-external-newwindow: true
    mainfont: "Public Sans"
    monofont: "Roboto Mono"
    code-link: true
    lightbox: true    
    smooth-scroll: true
    fig-cap-location: margin
    citation: true
    include-after-body:
      text: |
        <script type="application/javascript" src="/assets/darklight.js"></script>        

editor: visual

