project:
  type: website

license: CC-BY 4.0
author: 
  name: Josef Fruehwald
  
execute: 
  freeze: auto

website:
  title: "course_template"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Notes"
        href: notes/index.qmd
      - text: "About"
        href: about.qmd
  sidebar: 
    - title: "Home"
      logo: assets/logo.svg
      contents:
        - text: Home
          href: index.qmd
        - href: syllabus/syllabus.qmd
          text: Syllabus
        - href: syllabus/schedule.qmd
          text: Schedule
    - title: "Notes"
      contents:
        - text: Notes Home
          href: notes/index.qmd
        - section: Class Meetings
          contents: 
            - auto: notes/meetings/*

format:
  html:
    theme: 
      light: [flatly, styles/light.scss]
      dark: [darkly, styles/dark.scss]
    css: styles/styles.css
    toc: true
    fontsize: large
    smooth-scroll: true
    fig-cap-location: margin
    citation: true    

editor: visual

