### Accommodations Due to Disability

<details>**Accommodations Due to Disability**: In accordance with federal law, if you have a documented disability that requires academic accommodations, please inform your instructor as soon as possible during scheduled office hours.
In order to receive accommodations in a course, you must provide your instructor with a Letter of Accommodation from the Disability Resource Center (DRC).
The DRC coordinates campus disability services available to students with disabilities.
It is located on the corner of Rose Street and Huguelet Drive in the Multidisciplinary Science Building, Suite 407.
You can reach them via phone at (859) 257-2754, [[via email]{.underline}](https://www.uky.edu/universitysenate/drc@uky.edu) ([drc\@uky.edu](mailto:drc@uky.edu)) or visit their [[website]{.underline}](http://www.uky.edu/DisabilityResourceCenter) (uky.edu/DisabilityResourceCenter).
DRC accommodations are not retroactive and should therefore be established with the DRC as early in the semester as is feasible.</details>
