### Prep Week and Reading Days

<details>

**Prep Week and Reading Days**: Per *Senate Rules 5.2.5.6*, the last week of instruction of a regular semester is termed "Prep Week." This phrase also refers to the last three days of instruction of the summer session and winter intersession. The Prep Week rule applies to ALL courses taught in the fall semester, spring semester, and summer session, including those taught by distance learning or in a format that has been compressed into less than one semester or session. This rule does not apply to courses in professional programs in colleges that have University Senate approval to have their own calendar.

Make-up exams and quizzes are allowed during Prep Week. In cases of "Take Home" final examinations, students shall not be required to return the completed examination before the regularly scheduled examination period for that course. No written examinations, including final examinations, may be scheduled during the Prep Week. No quizzes may be given during Prep Week. No project/lab practicals/paper/presentation deadlines or oral/listening examinations may fall during the Prep Week unless it was scheduled in the syllabus AND the course has no final examination (or assignment that acts as a final examination) scheduled during finals week. (A course with a lab component may schedule the lab practical of the course during Prep Week if the lab portion does not also require a Final Examination during finals week.) Class participation and attendance grades are permitted during Prep Week. The *Senate Rules* permit continuing into Prep Week regularly assigned graded homework that was announced in the class syllabus.

For fall and spring semester, the Thursday and Friday of Prep Week are study days (i.e. "Reading Days"). There cannot be any required "interactions" on a Reading Day. "Interactions" include participation in an in-class or online discussion, attendance at a guest lecture, or uploading an assignment. See *Senate Rules 9.1* for a more complete description of required interactions.

</details>
