### Non-Discrimination Statement and Title IX Information

<details>

**Non-discrimination and Title IX policy**: In accordance with federal law, UK is committed to providing a safe learning, living, and working environment for all members of the University community.
The University maintains a comprehensive program which protects all members from discrimination, harassment, and sexual misconduct.
For complete information about UK's prohibition on discrimination and harassment on aspects such as race, color, ethnic origin, national origin, creed, religion, political belief, sex, and sexual orientation, please see [[the electronic version of *UK's Administrative Regulation 6:1* ("Policy on Discrimination and Harassment")]{.underline}](https://www.uky.edu/regs/ar6-1) (<https://www.uky.edu/regs/ar6-1>).
In accordance with Title IX of the Education Amendments of 1972, the University prohibits discrimination and harassment on the basis of sex in academics, employment, and all of its programs and activities.
Sexual misconduct is a form of sexual harassment in which one act is severe enough to create a hostile environment based on sex and is prohibited between members of the University community and shall not be tolerated.
For more details, please see [[the electronic version of *Administrative Regulations 6:2* ("Policy and Procedures for Addressing and Resolving Allegations of Sexual Harassment Under Title IX and Other Forms of Sexual Misconduct")]{.underline}](https://www.uky.edu/regs/sites/www.uky.edu.regs/files/files/ar/ar_6.2-interim-final_08_14_20_1.pdf) ([https://www.uky.edu/regs/sites/www.uky.edu.regs/files/files/ar/ar_6.2-in...](https://www.uky.edu/regs/sites/www.uky.edu.regs/files/files/ar/ar_6.2-interim-final_08_14_20_1.pdf)).
Complaints regarding violations of University policies on discrimination, harassment, and sexual misconduct are handled by the Office of Institutional Equity and Equal Opportunity (Institutional Equity), which is located in 13 Main Building and can be reached by phone at (859) 257-8927.
You can also visit [[Institutional Equity's website]{.underline}](https://www.uky.edu/eeo/) (<https://www.uky.edu/eeo>).

Faculty members are obligated to forward any report made by a student related to discrimination, harassment, and sexual misconduct to the Office of Institutional Equity.
Students can confidentially report alleged incidences through the [[Violence Intervention and Prevention Center]{.underline}](https://www.uky.edu/vipcenter/) (<https://www.uky.edu/vipcenter>), [[Counseling Center]{.underline}](https://www.uky.edu/counselingcenter/) (<https://www.uky.edu/counselingcenter>), or [[University Health Service]{.underline}](https://ukhealthcare.uky.edu/university-health-service/student-health) (<https://ukhealthcare.uky.edu/university-health-service/student-health>).

Reports of discrimination, harassment, or sexual misconduct may be made via the [[Institutional Equity's website]{.underline}](https://www.uky.edu/eeo/) (<https://www.uky.edu/eeo>); at that site, click on "Make a Report" on the left-hand side of the page.

</details>
