name: Build Site
on:
  push:
    branches: ["main"]

jobs:
  build-docs:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
      # - name: Install dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install gdal-bin libgdal-dev libcurl4-openssl-dev \
      #     libharfbuzz-dev libfribidi-dev libudunits2-dev libmagick++-dev \
      #     libfftw3-dev
      # - uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.11' 
      # - uses: r-lib/actions/setup-r@v2
      # - name: Cache packages
      #   uses: actions/cache@v4
      #   with:
      #     path: ${{ env.RENV_PATHS_ROOT }}
      #     key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-renv-

      # - name: Restore packages
      #   shell: Rscript {0}
      #   run: |
      #     if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
      #     renv::restore()
      # - name: Set up quarto
      #   uses: quarto-dev/quarto-actions/setup@v2
      # - name: Render and publish to gh pages
      #   uses: quarto-dev/quarto-actions/publish@v2
      #   with:
      #     target: gh-pages